cookie_names: [
  "COOKIE",
  "SET-COOKIE",
]
cookie_flags: [
  "HTTPONLY",
  "SAMESITE",
  "SECURE"
]
http_cors_header: [
  "ACCESS-CONTROL-ALLOW-ORIGIN"
]
http_deprecated_header: [
  "EXPECT-CT",
  "FEATURE-POLICY",
  "PUBLIC-KEY-PINS",
  "X-XSS-PROTECTION"
]
http_header: [
  "X-FRAME-OPTIONS:DENY,SAMEORIGIN",
  "X-XSS-PROTECTION:0",
  "CONTENT-SECURITY-POLICY:DEFAULT-SRC 'SELF';",
  "STRICT-TRANSPORT-SECURITY:MAX-AGE=;INCLUDESUBDOMAINS;PRELOAD",
  "X-CONTENT-TYPE-OPTIONS:NOSNIFF",
  "REFERRER-POLICY:STRICT-ORIGIN-WHEN-CROSS-ORIGIN,NO-REFERRER,SAME-ORIGIN"
]
http_header_api: [
  "X-FRAME-OPTIONS:DENY,SAMEORIGIN",
  "X-XSS-PROTECTION:0",
  "CONTENT-SECURITY-POLICY:DEFAULT-SRC 'SELF';",
  "STRICT-TRANSPORT-SECURITY:MAX-AGE=;INCLUDESUBDOMAINS;PRELOAD",
  "X-CONTENT-TYPE-OPTIONS:NOSNIFF"
]
http_information_disclosure_header: [
  "SERVER",
  "X-ASPNET-VERSION",
  "X-FESERVER",
  "X-POWERED-BY",
  "X-OWA-VERSION"
]
http_methods: [
  "TRACE",
  "TRACK"
]
